(deftheme adwaita-custom
  "Created 2012-09-18.")

(custom-theme-set-faces
 'adwaita-custom
 '(cursor ((((class color) (min-colors 89)) (:background "#00BBFF"))))
 '(border-color ((((class color) (min-colors 89)) (:background "#EDEDED"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#E6E6E6"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#C6C6C6" :background "white"))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#CCCCCC" :background "black"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#0084C8" :bold t))))
 '(region ((((class color) (min-colors 89)) (:foreground unspecified :background "#C2D5E9"))))
 '(dired-header ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(widget-button ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(success ((((class color) (min-colors 89)) (:bold t :foreground "#4E9A06"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#CE5C00"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#B50000"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#A020F0" :bold t))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#CFA708"))))
 '(font-lock-comment-face ((t (:foreground "#FF1467"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#1C8DD4"))))
 '(font-lock-keyword-face ((t (:foreground "#D96507" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#4E9A06"))))
 '(font-lock-type-face ((t (:foreground "#00CFBA"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#299AAF"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#F5666D" :bold t))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#0066CC"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#6799CC"))))
 '(highlight ((t (:background "#DFF7FF"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "white" :background "#77A4DD"))))
 '(erc-action-face ((((class color) (min-colors 89)) (:foreground "#F5666D"))))
 '(erc-button ((((class color) (min-colors 89)) (:foreground "#A8799C"))))
 '(erc-current-nick-face ((((class color) (min-colors 89)) (:bold t :foreground "#FF7092"))))
 '(erc-error-face ((((class color) (min-colors 89)) (:foreground "#F5666D" :bold t))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "black"))))
 '(erc-keyword-face ((((class color) (min-colors 89)) (:foreground "#F5666D"))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:bold t :foreground "#FF8CA7"))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#0084C8"))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "black"))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#4CB64A"))))
 '(magit-log-sha1 ((((class color) (min-colors 89)) (:foreground "#FF7092"))))
 '(magit-log-head-label-local ((((class color) (min-colors 89)) (:foreground "#4F78B5"))))
 '(magit-log-head-label-remote ((((class color) (min-colors 89)) (:foreground "#4CB64A"))))
 '(magit-branch ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(magit-section-title ((((class color) (min-colors 89)) (:bold t :foreground "#00578E"))))
 '(magit-item-highlight ((((class color) (min-colors 89)) (:background "#FEFFBF"))))
 '(magit-diff-add ((((class color) (min-colors 89)) (:bold t :foreground "#4CB64A"))))
 '(magit-diff-del ((((class color) (min-colors 89)) (:bold nil :foreground "#F5666D"))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:foreground "#00578E"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:bold t :foreground "#4F78B5"))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:foreground "#00578E"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:bold t :foreground "#9CBB43"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:foreground "#00578E"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:bold t :foreground "#9CBB43"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:bold t :foreground "#FF7092"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#FF7092"))))
 '(gnus-button ((((class color) (min-colors 89)) (:bold t :foreground "#00578E"))))
 '(gnus-cite-1 ((((class color) (min-colors 89)) (:foreground "#00578E"))))
 '(gnus-cite-2 ((((class color) (min-colors 89)) (:foreground "#0084C8"))))
 '(diff-added ((((class color) (min-colors 89)) (:bold t :foreground "#4E9A06"))))
 '(diff-removed ((((class color) (min-colors 89)) (:bold t :foreground "#F5666D"))))
 '(default ((((class color) (min-colors 89)) (:background "#EDEDED" :foreground "#2E3436")))))

(provide-theme 'adwaita-custom)
