#!/bin/sh
set -e

case "`uname`" in
    MINGW*|CYGWIN*)
        echo >&1 "don't run this on Windows; use link.bat instead"
        exit 1;;
esac

cd `dirname "$0"`
PWD=`pwd`

link_home() {
    SOURCE=$PWD/home/$1
    TARGET_DIR=`dirname "$HOME/$1"`/
    mkdir -p "$TARGET_DIR"
    ln -fs "$SOURCE" "$TARGET_DIR"
    printf "%s\n" "$SOURCE --> $TARGET_DIR"
}

link_home .bashrc
link_home .bash_profile
link_home .config/user-dirs.dirs
link_home .conkyrc
link_home .emacs.d/elisp/adwaita-custom-theme.el
link_home .emacs.d/elisp/gnuplot.el
link_home .emacs.d/elisp/solarized-custom-theme.el
link_home .emacs.d/elisp/tango-dark-custom-theme.el
link_home .emacs.d/elisp/wombat-custom-theme.el
link_home .emacs.d/init.el
link_home .gnupg/gpg-agent.conf
link_home .gtkrc-2.0
link_home .local/share/applications/mimeapps.list
link_home .profile
link_home .Rprofile
link_home .ttytterrc
link_home .xbindkeysrc
link_home .xinitrc
link_home .xmonad/xmonad.hs
link_home .Xresources
link_home .zprofile
link_home .zshrc
link_home sbin

patch -d"$HOME" -N -p0 -r- <home/.cabal/config.patch || :

if groups "$USER" | grep >/dev/null 2>&1 '\bwheel\b'
then :
else exit 0
fi

sudo -s -- <<EOF
set -e

mkdir -p /root/.emacs.d
cp -f home/.emacs.d/init.el /root/.emacs.d/
cp -f home/.Rprofile /root/
echo "$PWD/home/.emacs.d/init.el --> /root/.emacs.d/"

link_root() {
    SOURCE=$PWD/root/\$1
    TARGET_DIR=\`dirname "/\$1"\`/
    [ -f "/\$1.preserve" ] && return
    mkdir -p "\$TARGET_DIR"
    cp -fr "\$SOURCE" "\$TARGET_DIR"
    printf "%s\n" "\$SOURCE --> \$TARGET_DIR"
}

patch -d/ -N -p0 -r- <root/etc/chromium/default.patch || :
patch -d/ -N -p0 -r- \
      <root/etc/fonts/conf.avail.infinality/35-repl-custom.conf.patch || :
patch -d/ -N -p0 -r- <root/etc/inputrc.patch || :
patch -d/ -N -p0 -r- <root/etc/makepkg.conf.patch || :
patch -d/ -N -p0 -r- <root/etc/pacman.conf.patch || :
patch -d/ -N -p0 -r- <root/etc/pacman.d/gnupg/gpg.conf.patch || :
patch -d/ -N -p0 -r- <root/etc/ssh/sshd_config.patch || :

link_root bin/touchpad-ctl
link_root etc/dhclient.conf
link_root etc/environment-modules
link_root etc/environment-modules.d
link_root etc/iptables/iptables.rules
link_root etc/modprobe.d/nobeep.conf
link_root etc/modules-load.d/ppp_mppe.conf
link_root etc/pam.d/su
link_root etc/ppp/ip-up.d/01-routes.sh
link_root etc/resolv.conf.head
link_root etc/udev/rules.d/01-touchpad.rules
link_root etc/xdg/pacaur/config
link_root etc/X11/xorg.conf.d/10-monitor.conf
link_root etc/X11/xorg.conf.d/50-mouse-acceleration.conf
link_root etc/X11/xorg.conf.d/60-composite.conf

EOF
