#!/bin/sh
set -e

case "`uname`" in
    MINGW*|CYGWIN*)
        echo >&1 "don't run this on Windows; use link.bat instead"
        exit 1;;
esac

cd `dirname "$0"`
PWD=`pwd`

link_home() {
    source=$PWD/home/$1
    dest=${2-$1}
    destdir=`dirname "$HOME/$dest"`/
    mkdir -p "$destdir"
    ln -fs "$source" "$destdir"
    printf "%s\n" "$source --> $dest"
}

link_home .bashrc
link_home .bash_profile
link_home .config/user-dirs.dirs
link_home .config/xfce4/terminal
link_home .conkyrc
link_home .emacs.d/elisp/adwaita-custom-theme.el
link_home .emacs.d/elisp/gnuplot.el
link_home .emacs.d/elisp/solarized-custom-theme.el
link_home .emacs.d/elisp/tango-dark-custom-theme.el
link_home .emacs.d/elisp/wombat-custom-theme.el
link_home .emacs.d/init.el
link_home .ghci
link_home .gtkrc-2.0
link_home .local/share/applications/mimeapps.list
link_home .profile
link_home .Rprofile
link_home .tmux.conf
link_home .ttytterrc
link_home .xbindkeysrc
link_home .XCompose
link_home .xinitrc
link_home .xmonad/xmonad.hs
link_home .Xresources
link_home .zprofile
link_home .zshrc
link_home sbin .local/sbin

patch -d"$HOME" -N -p0 -r- <home/.cabal/config.patch || :

if groups "$USER" | grep >/dev/null 2>&1 '\bwheel\b'
then :
else exit 0
fi

sudo -s -- <<EOF
set -e

mkdir -p /root/.emacs.d
cp -f home/.emacs.d/init.el /root/.emacs.d/
cp -f home/.Rprofile /root/
echo "$PWD/home/.emacs.d/init.el --> /root/.emacs.d/"

link_root() {
    source=$PWD/root/\$1
    destdir=\`dirname "/\$1"\`/
    [ -f "/\$1.preserve" ] && return
    mkdir -p "\$destdir"
    cp -fr "\$source" "\$destdir"
    printf "%s\n" "\$source --> \$destdir"
}

patch -d/ -N -p0 -r- \
      <root/etc/fonts/conf.avail.infinality/35-repl-custom.conf.patch || :
patch -d/ -N -p0 -r- <root/etc/inputrc.patch || :
patch -d/ -N -p0 -r- <root/etc/makepkg.conf.patch || :
patch -d/ -N -p0 -r- <root/etc/pacman.conf.patch || :
patch -d/ -N -p0 -r- <root/etc/pacman.d/gnupg/gpg.conf.patch || :
patch -d/ -N -p0 -r- <root/etc/ssh/sshd_config.patch || :

link_root bin/touchpad-ctl
link_root etc/dhclient.conf
link_root etc/environment-modules
link_root etc/environment-modules.d
link_root etc/iptables/iptables.rules
link_root etc/modprobe.d/nobeep.conf
link_root etc/modules-load.d/ppp_mppe.conf
link_root etc/modules-load.d/virtualbox.conf
link_root etc/pam.d/su
link_root etc/ppp/ip-up.d/01-routes.sh
link_root etc/sysctl.avail/99-sysrq.conf
link_root etc/systemd/logind.conf.d/50-ignore-lid-switch.conf
link_root etc/systemd/system/netctl-auto-monitor@.service
link_root etc/systemd/system/tmux@.service
link_root etc/udev/rules.d/01-touchpad.rules
link_root etc/xdg/pacaur/config
link_root etc/X11/xorg.conf.d/10-monitor.conf
link_root etc/X11/xorg.conf.d/50-mouse-acceleration.conf
link_root etc/X11/xorg.conf.d/50-natural-scroll.conf
link_root etc/X11/xorg.conf.d/50-palm-detect.conf
link_root etc/X11/xorg.conf.d/60-composite.conf
link_root usr/local/bin/netctl-auto-monitor
link_root usr/local/bin/smartdnotify

EOF
