#!/bin/sh
set -eu
ls /root >/dev/null # make sure we are root

configure() (
    umask 077
    cat >>/etc/postfix/main.cf <<EOF
myorigin = $origin
relayhost = [$relay]
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/smtp_auth
smtp_sasl_security_options = noanonymous
EOF
    cat >/etc/postfix/smtp_auth <<EOF
[$relay] $auth
EOF
    postmap /etc/postfix/smtp_auth
)

name=`basename "$0"`

# template:
#
#   origin=foo.org
#   auth=qux@bar.org:pw
#   relay=smtp.bar.org
#
. ".local/etc/${name}.sh"
exit
pacman -S --needed postfix
systemctl enable postfix
systemctl start postfix
# deb: apt-get -y install postfix # choose "No configuration"
configure
systemctl reload postfix
# deb: /etc/init.d/postfix start
