#!/bin/sh

# Wine in general
sudo pacman -S wine wine_gecko wine-mono lib32-ncurses lib32-mpg123


# For Hearthstone:

sudo pacman -S lib32-libldap
winecfg
# set 'dbghelp' to disabled & 'wininet' to builtin
