#!/bin/bash

#
# /etc/xdg/pacaur/config
#

# The following options are commented out with their default values listed.
# If you wish to use different values, uncomment and update the values.
# The Color and VerbosePkgLists options can be enabled in /etc/pacman.conf.
# The makepkg environment variables are also fully honored.
clonedir=$HOME/.cache/aur              # clone directory
editor=less                            # build files editor
displaybuildfiles=diff                 # display build files (none|diff|full)
#fallback=true                         # pacman fallback to the AUR
#silent=false                          # silence output
#sortby=popularity                     # sort method (name|votes|popularity)
sudoloop=true                          # prevent sudo timeout

