#!/bin/sh

if [ $# -ne 4 ]
then
    prog=`basename "$0"`
    printf >&2 "Usage: %s <oldbase-in> <oldchanged-in> <newbase-in> <newchanged-out>\n" "$prog"
    exit 1
fi

dir=`mktemp -d` || exit
trap 'rm -fr "$dir"' 0 1 2 15 || exit

git -C "$dir" init -q || exit
git -C "$dir" config user.name nobody || exit
git -C "$dir" config user.email nobody@nobody || exit

cp -Rp "$1" "$dir/_" || exit
git -C "$dir" add -A || exit
git -C "$dir" commit -q --allow-empty -m Original || exit

git -C "$dir" checkout -q -b old || exit
rm -fr "$dir/_" || exit
cp -Rp "$2" "$dir/_" || exit
git -C "$dir" add -A || exit
git -C "$dir" commit -q --allow-empty -m Old || exit

git -C "$dir" checkout -q master || exit
rm -fr "$dir/_" || exit
cp -Rp "$3" "$dir/_" || exit
git -C "$dir" add -A || exit
git -C "$dir" commit -q --allow-empty -m New || exit

git -C "$dir" cherry-pick old
e=$?
if [ $e -ne 0 ]; then
    git -C "$dir" status
fi

mv "$dir/_" "$4"

exit $e
