#!/bin/sh
set -e

if [ $# -eq 0 ]
then
    cat >&2 <<EOF
usage: `basename "$0"` PATH...

Make each of the PATHs absolute and normalized.  If a path is already
absolute, the path will remain the equivalent to the original.  On
POSIX-compliant systems, symbolic links in PWD are not resolved.

The paths are not required to exist physically.
EOF
    exit 1
fi

for p
do
    if printf '%s' "$p" | grep >/dev/null '^/'
    then
        normpath "$p"
    else
        # note: on heirloom shell `pwd` does in fact resolves symlinks,
        #       which is a bit unusual
        joinpath "`pwd`" "$p"
    fi
done
