#!/bin/sh
#
# Example: . activate-env /opt/llvm-3.5.2

usage() {
    prog=`basename "$0"`
    printf >&2 "usage: . %s <prefix>\n" "$prog"
    return 2
    exit 2
}

if [ $# != 1 ]
then
    usage
fi
case $1 in
    -*) usage;;
esac

prefix=$1
C_INCLUDE_PATH=${C_INCLUDE_PATH+:}$C_INCLUDE_PATH
C_INCLUDE_PATH=$prefix/include$C_INCLUDE_PATH
CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH+:}$CPLUS_INCLUDE_PATH
CPLUS_INCLUDE_PATH=$prefix/include$CPLUS_INCLUDE_PATH
LD_LIBRARY_PATH=${LD_LIBRARY_PATH+:}$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$prefix/lib$LD_LIBRARY_PATH
LIBRARY_PATH=${LIBRARY_PATH+:}$LIBRARY_PATH
LIBRARY_PATH=$prefix/lib$LIBRARY_PATH
PATH=$prefix/bin:$PATH
export C_INCLUDE_PATH CPLUS_INCLUDE_PATH LD_LIBRARY_PATH LIBRARY_PATH PATH
