#!/bin/sh
set -e

# 1. trailing comments prevent the empty line before a "}" from being deleted
sed -i"~" 's|^\([ 	]*};\{0,1\}\)$|\1 // REMOVE_ME_WXXN3AHCGKWYXDY|' "$@"
sed -i"~" 's|^\([ 	]*default:\)$|\1 // REMOVE_ME_WXXN3AHCGKWYXDY|' "$@"

clang-format -i "$@"

# 2. add empty line after access modifiers
sed -i"~" 's|^\([ 	]*[[:alnum:]]\{1,\}:\)$|\1\
|' "$@"

# 3. work around the fact that "SpaceAfterTemplateKeyword" isn't supported
# 4. undo the effects of #1
sed -i"~" 's|template <|template<|;s|[ 	]*// REMOVE_ME_WXXN3AHCGKWYXDY$||' "$@"
