#!/bin/sh
set -e
case ${1--} in
    -*)
        cat >&2 <<EOF
usage: `basename "$0"` <path>
EOF
        exit 1
        ;;
esac
root=$1
[ -f "$root/etc/.installed" ] || {
    # initial install
    mkdir -m 0755 -p "$root"
    pacstrap -c "$root" base sudo

    # Workaround for https://bugs.archlinux.org/task/45903
    cat /dev/null >"$root/etc/securetty"
    for pts in pts/{0,1,2,3,4,5,6,7,8,9}; do
        echo "$pts" >>"$root/etc/securetty"
    done

    # configure locale
    echo LANG=en_US.UTF-8 >"$root/etc/locale.conf"
    echo en_US.UTF-8 UTF-8 >"$root/etc/locale.gen"
    # indirectly run locale-gen (locale-gen is run when glibc is reinstalled)
    pacstrap -c "$root" glibc

    touch "$root/etc/.installed"
}
exec systemd-nspawn -b -D "$root"
