#!/bin/sh
#
# Strips whitespace from the end of each line without deleting any carriage
# returns.
#
# Note: there is a literal tab character in pattern.
#
# A recursion depth limit may be needed to prevent SSHFS from dropping the
# connection, e.g.:
#
#   find . -maxdepth 2 ...
#
find . -type f "(" \
    -name '*.c' \
    -o \
    -name '*.cc' \
    -o \
    -name '*.cpp' \
    -o \
    -name '*.h' \
    -o \
    -name '*.hh' \
    -o \
    -name '*.hpp' \
    -o \
    -name '*.inl' \
    -o \
    -name '*.py' \
    -o \
    -name "doxyfile" \
    ")" -exec sed -i 's/[ 	]\+$//' "{}" \;
