#!/bin/sh
#
# Usage: download URL
#
# Downloads from the given URL (via `curl` or `wget`) and returns the result
# via standard output.

set -e

if [ -z "${1+x}" ]
then
    printf >&2 "Usage: %s URL\n" "$0"
    exit 1
fi

if command >/dev/null 2>&1 -v curl
then
    curl -fL -- "$1"
else
    if command >/dev/null 2>&1 -v wget
    then
        wget -O- -- "$1"
    else
	printf >&2 "%s: missing 'curl' or 'wget'\n" "$0"
	exit 127
    fi
fi
