#!/bin/sh
# Get v4l2loopback from https://github.com/umlaeute/v4l2loopback
set -e
sudo modprobe v4l2loopback
ffmpeg -f x11grab -r 15 -s 1280x720 -i :0.0+0,0 -vcodec rawvideo \
       -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0
