#!/bin/sh
#
# Finds duplicate files.
#
# Change to the directory you want to check, then run the script to check the
# directory recursively for duplicate files.
#
# Source:  http://joescat.com/linux/rem-dups.html

strip_hash='s/^[0-9a-f]* *\*\{0,1\}//'
escape_quotes="s/'/'\"'\"'/g"
quote_lines='s/^\(..*\)$/'"#rm '\1'/"

find "$@" -type f -exec md5sum "{}" + | \
    sort --key=1,32 | \
    uniq -w 32 -d --all-repeated=separate | \
    sed "$strip_hash;$escape_quotes;$quote_lines"
