#!/bin/sh
set -e
if [ "$CABAL_SANDBOX_CONFIG" ]
then set -- cabal sandbox hc-pkg -- check "$@"
else set -- ghc-pkg check "$@"
fi
# suppress the useless warnings
pattern="/^ *Warning: haddock-.* doesn't exist or isn't a/d"
{
    "$@" 3>&1 1>&2 2>&3 3>&- | sed "$pattern"
} 3>&1 1>&2 2>&3 3>&-
