#!/usr/bin/env python
import subprocess, sys

opts = ["ghc-pkg"]
args = []
process_opts = True
for arg in sys.argv[1:]:
    if process_opts:
        if arg == "--":
            process_opts = False
            continue
        if arg.startswith("-"):
            opts.append(arg)
            continue
    args.append(arg)

for arg in args:
    ret = subprocess.call(opts + ["unregister", "--", arg])
    if ret != 0:
        sys.exit(ret)
