#!/bin/sh
set -e
key=DDAD82A7
version=$1
case $version in
    *.*.*.*)
        exec git tag -a -s -u "$key" -m "directory $version" "v$version";;
    *)
        prog=`basename "$0"`
        cat >&2 <<EOF
usage: $prog VERSION

where VERSION is of the X.X.X.X format
EOF
        exit 2;;
esac
