#!/bin/sh
set -eu

[ "${1-}" ] && [ "${2-}" ] || {
    cat >&2 <<EOF
Usage: `basename "$0"` REMOTE_URL REMOTE_BRANCH [READ_TREE_ARG...]

Merges a REMOTE_BRANCH from another repository at REMOTE_URL into the current
branch.

Here, '[READ_TREE_ARG...]' are additional arguments passed to 'git-read-tree'
such as '--prefix=<...>/'.  Note that the prefix is relative to the root.

Example: git-merge-subtree git@host:foo.git master --prefix=foo/
EOF
    exit 1
}
remote_url=$1
remote_branch=$2
shift 2

remote=tmp-git-merge-subtree-remote
git remote add -f "$remote" "$remote_url"
git merge --no-commit --allow-unrelated-histories -s ours "$remote/$remote_branch"
git read-tree "$@" -u "$remote/$remote_branch"
git commit
git remote rm "$remote"
