#!/bin/sh
# show the entire history of a Git repo as a colored tree in the terminal

version_ge() {
    [ "$1" -gt "$4" ] || {
        [ "$1" -eq "$4" ] && {
            [ "$2" -gt "$5" ] || {
                [ "$2" -eq "$5" ] && [ "$3" -ge "$6" ]
            }
        }
    }
}

ver=`git --version | sed 's/[^0-9]*\([.0-9]\{1,\}\).*/\1/'`
ver1=`printf "%s" "${ver}" | cut -f 1 -d .`
ver2=`printf "%s" "${ver}" | cut -f 2 -d .`
ver3=`printf "%s" "${ver}" | cut -f 3 -d .`

# %C(auto) is only supported on git >= 1.8.3
if version_ge "${ver1}" "${ver2}" "${ver3}" 1 8 3; then
    auto="%C(auto)"
fi

fmt="${auto}%h %C(green)%ad%C(reset)${auto}%d %s%n"
exec git log --all --date=short --decorate --full-history --graph \
             --pretty=format:"${fmt}" "$@"
