#!/usr/bin/env python
# Requires: https://github.com/joeyh/github-backup
import datetime, getpass, json, os, subprocess, time, sys
try:
    import configparser
except ImportError:
    import ConfigParser

def expandpath(path, pwd=None):
    if path is not None:
        path = os.path.expandvars(os.path.expanduser(path))
        if pwd is not None:
            path = os.path.join(pwd, path)
    return path

def mkdirs(path):
    import os
    try:
        os.makedirs(path)
    except OSError:
        pass

def curl(url):
    try:
        result = subprocess.check_output(["curl", "-fsLS", url])
    except subprocess.CalledProcessError:
        return
    return json.loads(result.decode("utf8"))

def github_backup(account, username=None, password=None, env=None):
    env = dict(os.environ if env is None else env)
    if password:
        env["GITHUB_USER"]     = username or account
        env["GITHUB_PASSWORD"] = password
    subprocess.check_call(["github-backup", account], env=env)

def get_reset_time(resource="core"):
    result = curl("https://api.github.com/rate_limit")
    if not result:
        return
    resource = result["resources"][resource]
    if resource["remaining"] > 0:
        return
    reset_time = datetime.datetime.fromtimestamp(resource["reset"])
    return reset_time

def backup_account(account, username=None, password=None, env=None):
    mkdirs(account)
    os.chdir(account)

    interval = datetime.timedelta(minutes=1)
    while True:
        try:
            github_backup(account, username, password, env)
        except subprocess.CalledProcessError as e:
            print("Error: " + str(e.returncode))
        else:
            break
        reset_time = get_reset_time()
        if reset_time:
            next_attempt = reset_time
        else:
            next_attempt = datetime.datetime.now() + interval
            interval *= 2
        print("Sleeping until {0} ...".format(next_attempt))
        time.sleep((next_attempt - datetime.datetime.now()).total_seconds())

def main():
    pwd = os.path.dirname(__file__)
    config = configparser.RawConfigParser()
    config.read(os.path.splitext(__file__)[0] + ".conf")

    accounts = config["config"]["accounts"].split()
    location = expandpath(config["config"]["location"], pwd)
    home     = expandpath(config["config"].get("home", None), pwd)
    login    = config["config"].get("login", "").split(maxsplit=1)

    if len(login) == 2:
        username, password = login
    elif len(login) == 1:
        username = login[0]
        password = getpass.getpass("Password for {0}: ".format(username))
    else:
        username = None
        password = None

    env = dict(os.environ)
    if home is not None:
        env["HOME"] = home

    mkdirs(location)
    os.chdir(location)
    for account in accounts:
        backup_account(account, username, password, env)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        exit(2)
