#!/bin/sh
set -eu
prog=`basename "$0"`

usage() {
    cat >&2 <<EOF
usage: $prog <original-user>/<project> [args...]
EOF
    exit 1
}
if [ $# -lt 1 ]
then
    usage
fi
case $1 in
    -*) usage;;
esac

if [ -f "$HOME/.config/$prog.sh" ]
then
    . "$HOME/.config/$prog.sh"
else
    cat >&2 <<EOF
$prog: config file (~/.config/$prog.sh) is missing

    You must define the 'forkroot' variable in the config file.
    A simple example would be:

        forkroot=github.com:<username>

    You can optionally define the 'destdir' variable.

EOF
    exit 1
fi

url=$1
case $url in
    http*://github.com/*/*)
        user=`printf "%s" "$url" | cut -d / -f 4`
        proj=`printf "%s" "$url" | cut -d / -f 5`
        ;;
    github.com/*/*)
        user=`printf "%s" "$url" | cut -d / -f 2`
        proj=`printf "%s" "$url" | cut -d / -f 3`
        ;;
    */*)
        user=`printf "%s" "$url" | cut -d / -f 1`
        proj=`printf "%s" "$url" | cut -d / -f 2`
        ;;
    *)
        printf >&2 "%s: invalid repo name: %s\n" "$prog" "$url"
esac

if [ "${destdir+x}" ]
then
    printf >&2 "%s\n" "note: cloning to $destdir"
    cd "$destdir"
fi
git-clone-both https://github.com/$user/$proj git@$forkroot/$proj
