#!/bin/sh
set -e

if [ $# -eq 0 ]
then
    cat >&2 <<EOF
usage: `basename "$0"` PATH...

Join the given PATHs, inserting slashes and normalizing as needed.

The paths are not required to exist physically.
EOF
    exit 1
fi

joined=$1
shift
for p
do
    joined=$joined/$p
done
normpath "$joined"
