#!/bin/bash

read -r -d "" USAGE <<EOF
Usage: $(basename $0) PATH...
Joins together the given PATHs, inserting slashes and simplifying as needed
(removing unnecessary '..', '.', and '/').
EOF
if [ "$#" = 0 ]; then
    echo >&2 "$USAGE"
    exit 1
fi

JOINED=$1
shift 1
for P in "$@"; do
    JOINED="$JOINED/$P"
done
normpath "$JOINED"
