#!/bin/sh

wd=
cleanup() {
    set +e
    if [ "$wd" ]
    then
        rm -r "$wd"
        wd=
    fi
    [ "$1" ] || exit 1
}
trap cleanup 1 2 15
set -e
wd=`mktemp -d .makel.XXXXXX`
set +e
# note: set -e interacts poorly with traps
(
    set -e

    commandfile=$wd/command
    logfile=$wd/log
    statusfile=$wd/status

    printf >"$commandfile" make
    for arg
    do
        printf >>"$commandfile" " '"
        printf '%s' "$arg" | sed >>"$commandfile" s/\'/\''\\'\'\'/g
        printf >>"$commandfile" "'"
    done
    command=`cat "$commandfile"`

    {
        set +e
        script 2>/dev/null -eqc "$command" /dev/null
        echo >&2 $?
    } </dev/null 2>"$statusfile" | less -R
    status=`cat "$statusfile"`
    exit 2>/dev/null "$status"

)
status=$?
cleanup end
trap - 1 2 15
exit "$status"
