#!/bin/sh
watching=n &&                           # avoid duplicate "Watching" messages
while :; do
    while :; do
        if make -q "$@"; then
            break
        fi &&
        watching=n &&
        printf '\033[34;1m[~]\033[0;1m Building...\033[0m\n' &&
        make "$@" || {
            printf '\033[31;1m[!] ERROR.\033[0m\n' &&
            printf '\033[33;1m[o]\033[0;1m Watching...\033[0m\n' &&
            watching=y &&
            break
        }
    done &&
    if [ "${watching}" = n ]; then
        printf '\033[32;1m[o]\033[0;1m Watching...\033[0m\n' &&
        watching=y
    fi &&
    inotifywait -qq -r -e close_write . || exit
done
