#!/bin/sh
set -eu
if [ $# -ne 1 ]; then
    cat >&2 <<EOF
usage: `basename "$0"` <dir>

For each file in the given <dir> and its transitive sub-directories, in
ascending order of path, execute md5sum relative to <dir>.
EOF
fi
exec for-dir "$1" md5sum
