#!/bin/sh

guard=G_`dd ibs=1 count=20 </dev/urandom 2>/dev/null |
         encode -s -w0 -u b32 |
         dd ibs=1 count=29 2>/dev/null`

cat <<EOF
#ifndef $guard
#define $guard
#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif
#endif
EOF
