#!/bin/sh
# Make a self-extracting script that executes "INPUT_DIR/autorun".
#
# Usage: make-setup INPUT_DIR OUTPUT_FILE

if [ $# -ne 2 ]
then
    cat >&2 <<EOF
usage: `basename "$0"` INPUT_DIR OUTPUT_FILE
EOF
    exit 1
fi

path=`printf '%s' "$1" | sed s/'/'"'"'/g`
len_guess=0
len_true=1
while [ "$len_true" != "$len_guess" ]
do
    len_guess=$len_true
    cat >"$2" <<EOF
#!/bin/sh
tail -c +$len_guess "\$0"|tar x
'$path'/autorun
exit
EOF
    len_true=`wc <"$2" -c`
    len_true=`expr "$len_true" + 1`
done
tar >>"$2" cf - "$1"
chmod +x "$2"
