#!/bin/sh
set -eu
if [ -z "${1+x}" ]
then
    prog=`basename "$0"`
    printf >&2 'usage: %s IN_FILE [OUT_FILE] [-- ARGS...]\n' "$prog"
    exit 1
fi
in=$1
shift
if [ "${1+x}" ] && [ "$1" != -- ]
then
    out=$1
    shift
else
    out=`printf '%s' "$in" | sed 's|\(\.[^./]*\)\{0,1\}$|.gif|'`
fi
tmpdir=${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}
palette=$tmpdir/mp42gif-palette.png
filters="fps=10,scale=240:-1:flags=lanczos"
ffmpeg -v warning -i "$in" -vf "$filters,palettegen" "$@" -y "$palette"
ffmpeg -v warning -i "$in" -i "$palette" \
       -lavfi "$filters [x]; [x][1:v] paletteuse" "$@" -y "$out"
# note: if this is too large, just use the naive approach
# ffmpeg -i "$in" "$out"
