#!/usr/bin/env python3
# Rename files using a transformation that supports datetime.

import argparse
import functools
import sys
from typing import Optional

import mv_sed

def main() -> Optional[str]:
    parser = argparse.ArgumentParser(description=(
        "Renames files using a transformation that supports datetimes."
    ))
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="don't actually rename anything")
    parser.add_argument("-t", "--transformation", default='Command(["sed"])',
                        help="Transformation expression")
    parser.add_argument("pattern", help="Pattern to match")
    parser.add_argument("replacement", help="Replacement")
    parser.add_argument("files", nargs="+", help="filename")
    args = parser.parse_args()
    transformation = functools.partial(
        mv_sed.transform_date,
        [(args.pattern, args.replacement)],
    )
    try:
        mv_sed.mv_transform(
            dry_run=args.dry_run,
            transformation=transformation,
            files=args.files,
        )
    except mv_sed.Error as e:
        return f"{parser.prog}: {e}"
    return None

if __name__ == "__main__":
    sys.exit(main())
