#!/usr/bin/env python3
# Rename files using a custom transformation.

import argparse
import functools
import sys
from typing import Optional

import mv_sed

def main() -> Optional[str]:
    parser = argparse.ArgumentParser(
        description="Renames every file using a Transformation.")
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="don't actually rename anything")
    parser.add_argument("-t", "--transformation", default='Command(["sed"])',
                        type=mv_sed.Transformation.parse,
                        help="Transformation expression")
    parser.add_argument("arg", help="Transformation argument")
    parser.add_argument("files", nargs="+", help="filename")
    args = parser.parse_args()
    transformation = functools.partial(args.transformation, args.arg)
    try:
        mv_sed.mv_transform(args.dry_run, transformation, args.files)
    except mv_sed.Error as e:
        return f"{parser.prog}: {e}"
    return None

if __name__ == "__main__":
    sys.exit(main())
