#!/bin/sh
set -e

if [ $# -ne 2 ]
then
    cat >&2 <<EOF
usage: `basename "$0"` TARGET SOURCE

Construct a normalized relative path from the SOURCE directory to the TARGET
file or directory.

The paths are not required to exist physically.
EOF
    exit 1
fi

# check whether `stringB` is a prefix of `stringA` and
# obtain the length of `stringB`
#
# inputs:
#   - 1:    `stringA`
#   - 2:    `stringB`
#
# output:
#   - ret:  length of `stringB`
#
not_prefix_of() {
    _1=`printf '%s' "$1" | wc -c`
    ret=`printf '%s' "$2" | wc -c`
    # if stringB is longer, return unchanged
    if [ "$_1" -lt "$ret" ]
    then
        return
    fi
    # check whether stringB is a prefix of stringA
    _1=`printf '%s' "$1" | dd 2>/dev/null bs=1 count="$ret"`
    [ "$_1" != "$2" ]
}

# remove `stringB` from the beginning of `stringA`; if `stringB` is not a
# prefix of `stringA`, `stringA` is returned instead
#
# this is a workaround for the absence of `${var##prefix}` or `${var#prefix}`
# in older shells; note however that this function does not allow patterns
#
# inputs:
#   - 1:    `stringA`
#   - 2:    `stringB`
#
# output:
#   - ret:  `stringA` with possibly `stringB` removed from the beginning
#
strip_prefix() {
    # if the pattern is not a prefix of the original string, return unchanged
    if not_prefix_of "$1" "$2"
    then
        ret="$1"
    else
        # obtain substring
        ret=`expr "$ret" + 1`
        ret=`printf '%s' "$1" | tail -c +"$ret"`
    fi
}

# make both of them absolute only if at least one of them is absolute
target=$1
common=$2
if printf '%s' "$target" | grep >/dev/null '^/' ||
   printf '%s' "$common" | grep >/dev/null '^/'
then
    target=`abspath "$target"`
    common=`abspath "$common"`
else
    target=./`normpath "$target"`
    common=./`normpath "$common"`
fi

# ensure the SOURCE path is a directory
if printf '%s' "$common" | grep >/dev/null '/$'
then :
else
    common=$common/
fi

# find common prefix
back=
while not_prefix_of "$target" "$common"
do
    common=`dirname "$common"`
    back=../$back
done
strip_prefix "$target" "$common"
normpath "$back$ret"
