#!/usr/bin/env python
import base64, hashlib, re, sys

def fingerprint(key):
    digest = hashlib.md5(key).hexdigest()
    return ":".join(a + b for a, b in zip(digest[::2], digest[1::2]))

first = True
for fn in sys.argv[1:]:
    if not first:
        print("")
    first = False
    print("# {0}".format(fn))
    with open(fn) as f:
        for line in f:
            m = re.match("(ssh-rsa\s+)(\S+)(.*)", line)
            if m:
                pre, pubkey, post = m.groups()
                pubkey = base64.b64decode(pubkey.encode("ascii"))
                print("{0}{1}{2}".format(pre, fingerprint(pubkey), post))
            else:
                sys.stdout.write(line)
