#!/usr/bin/env python

def fingerprint(key):
    import hashlib
    digest = hashlib.md5(key).hexdigest()
    return ":".join(a + b for a, b in zip(digest[::2], digest[1::2]))

import base64, re, os, sys
fns = sys.argv[1:]
if not fns:
    import glob
    fns = glob.glob(os.path.normpath(os.path.expanduser("~/.ssh/*.pub")))

first = True
for fn in fns:
    if not first:
        print("")
    first = False
    print("# {0}".format(fn))
    with open(fn) as f:
        for line in f:
            m = re.match("(?:ssh-rsa|ecdsa-[\w-]+)\s+(\S+)(.*)", line)
            if m:
                key, comment = m.groups()
                fp = fingerprint(base64.b64decode(key.encode("ascii")))
                print("{0} {1}{2}".format(fp, key[-6:], comment))
            else:
                sys.stdout.write(line)
