#!/bin/sh
#
# If you want to update the apps, delete:
#
#     ~/.local/src/tg{,-export}
#
set -eu
mkdir -p "$HOME/.local/src"
(
    set -eu
    cd "$HOME/.local/src"
    [ -d tg ] ||
        git clone --recursive https://github.com/vysheng/tg
    [ -x tg/bin/telegram-cli ] || (
        set -eu
        cd tg
        ./configure
        make -j`nproc`
    )
    [ -d tg-export ] ||
        git clone --recursive https://github.com/gumblexi/tg-export
)
exec python3 "$HOME/.local/src/tg-export/export.py" \
          -e "$HOME/.local/src/tg/bin/telegram-cli" "$@"
