#!/bin/sh
set -e

: ${BIBTEX=bibtex}
: ${LATEX=pdflatex}
: ${LATEXFLAGS='-interaction nonstopmode'}

if [ "$1" = --silent ]
then
    silent=t
    shift
fi
if [ -z "${1+x}" ]
then
    printf >&2 '%s: expected filename\n' "$0"
    exit 1
fi
input=$1
shift

cleanup() {
    set +e
    if [ "$wd" ]
    then
       find "$wd" -type f -not -name "*.bib" -not -name "*.out" \
            -not -name "*.pdf" -not -name "*.tex" -exec cp "{}" . \;
       rm -r "$wd"
       wd=
    fi
    [ "$1" ] || exit 1
}

bib=
if [ -e "$input.bib" ]
then bib=t
fi

run() {
    wd=
    prev_traps=`trap`
    trap cleanup 1 2 15
    wd=`mktemp -d "tmp.$input.XXXXXX"`
    if [ $# -ne 0 ]
    then
        cp "$@" "$wd/"
    fi
    cp 2>/dev/null -f "$input.tex" "$input.aux" "$input.bib" "$input.toc" \
       "$input.thm" "$input.out" "$input"Notes.bib "$wd/" || :
    (
        cd "$wd"
        "$LATEX" $LATEXFLAGS "$input"
        if [ "$bib" ]
        then
            "$BIBTEX" $BIBTEXFLAGS "$input"
            "$LATEX"  $LATEXFLAGS  "$input"
        fi
        if grep 'Rerun to get cross-references' "$input.log"
        then
            "$LATEX" $LATEXFLAGS "$input"
        fi
        if grep 'Rerun to get outlines right' "$input.log"
        then
            "$LATEX" $LATEXFLAGS "$input"
        fi

        mv *.pdf ..;
    )
    cleanup end
    trap - 1 2 15
    eval "$prev_traps"
}

if [ "$silent" ]
then run "$@" >/dev/null || { x=$?; cat "$input.log"; exit "$x"; }
else run "$@"
fi
