#!/bin/sh
set -eu
trash_dir=$HOME/trash/`date -u +"%Y/%m/%d/%H%M%S"`
mkdir -p "${trash_dir}"
cat >&2 <<EOF
$@ -> ${trash_dir}/
EOF
for arg
do
    printf "%s/%s\n" "$PWD" "$arg" >>"${trash_dir}/.trash_origin"
done
mv "$@" "${trash_dir}"/
