#!/bin/sh
set -eu

load_config() {
    . "$1"

    if [ -z "${remote_host-}" ]; then
        prog=`basename "$0"`
        printf >&2 "%s: missing 'remote_host' from: %s\n" "$prog" "$1"
        exit 1
    fi
    if [ -z "${remote_dir-}" ]; then
        prog=`basename "$0"`
        printf >&2 "%s: missing 'remote_dir' from: %s\n" "$prog" "$1"
        exit 1
    fi
    if [ -z "${url_prefix-}" ]; then
        prog=`basename "$0"`
        printf >&2 "%s: missing 'url_prefix' from: %s\n" "$prog" "$1"
        exit 1
    fi
    case $remote_dir in
        *"'"*)
            prog=`basename "$0"`
            printf >&2 "%s: 'remote_dir' cannot contain apostrophes\n" "$prog"
            exit 1;;
    esac
}

if [ $# -lt 1 ]
then
    prog=`basename "$0"`
    printf >&2 "usage: %s <url>...\n" "$prog"
    exit 2
fi

for path
do
    case $path in
        *://*) ;;
        *)
            printf >&2 'Not a valid URL: %s\n' "$path"
            exit 1;;
    esac
    for config in "$HOME"/.config/upload/*.conf
    do
        load_config "$config"
        case $path in
            "$url_prefix"*)
                bn=`basename "$path"`
                ssh "$remote_host" 'sudo rm '"'$remote_dir'"/"$bn"
                continue 2;;
        esac
    done
    printf >&2 'Could not find corresponding config file for: %s\n' "$path"
    exit 1
done
