#!/bin/sh
set -eu
#UPLOAD_REMOTE=<host>
#UPLOAD_REMOTE_URL=<url>

prog=`basename "$0"`
if [ -z "$UPLOAD_REMOTE" ] || [ -z "$UPLOAD_REMOTE_URL" ]
then
    printf >&2 "%s: UPLOAD_REMOTE and UPLOAD_REMOTE_URL must be set\n" "$prog"
    exit 1
fi
if [ -z "$1" ]
then
    printf >&2 "usage: %s FILE\n" "$prog"
    exit 2
fi

for orig
do
    new=`hashname -nps -- "$orig"`
    case $new in
        "") exit 1;;
        *.*) ;;
        *) new=$new.txt;;
    esac
    printf "Uploading $orig to:\n  %s/t/%s\n" "$UPLOAD_REMOTE_URL" "$new"
    rsync -P --chmod=644 "$orig" "$UPLOAD_REMOTE:/var/www/t/$new"
done
