#!/bin/sh
set -e
#UPLOAD_REMOTE=<host>
#UPLOAD_REMOTE_URL=<url>

prog=`basename "$0"`
if [ -z "$UPLOAD_REMOTE" ] || [ -z "$UPLOAD_REMOTE_URL" ]
then
    printf >&2 "%s: UPLOAD_REMOTE and UPLOAD_REMOTE_URL must be set\n" "$prog"
    exit 1
fi
if [ -z "$1" ]
then
    printf >&2 "usage: %s FILE\n" "$prog"
    exit 2
fi

orig=$1
new=`hashname -nps "$orig"`
case $new in
    *.*) ;;
    *) new=$new.txt;;
esac
rsync -P "$orig" "$UPLOAD_REMOTE:/var/www/t/$new"
ssh "$UPLOAD_REMOTE" chmod 644 "/var/www/t/$new"
printf "%s/t/%s\n" "$UPLOAD_REMOTE_URL" "$new"
