#!/bin/sh
set -eu
prog=`basename "$0"`
remote=rogue
waifu2xdir='$HOME/.local/opt/waifu2x'
torchdir='$HOME/.local/opt/torch'

if [ $# -lt 1 ]; then
    printf >&2 "%s\n" "usage: $prog INPUT_FILE.{jpg,png} [OUTPUT_FILE.png]"
    exit 1
fi

input=$1
output=${2-`printf "%s" "$input" | sed 's/\.[^.]\{1,\}$//'`.upscaled.png}

case $input in
    *.jpg) ext=jpg;;
    *.png) ext=png;;
    *)
        printf >&2 "%s\n" "$prog: unknown image type: $input"
        exit 1;;
esac

hash=`sha1sum "$input" | cut -d " " -f 1`

rsync -Pv "$input" "$remote:/tmp/waifu2x-$USER.$hash-in.$ext"
ssh -T "$remote" <<EOF
. "$torchdir/install/bin/torch-activate" &&
cd "$waifu2xdir" &&
printf "%s\n" "Processing (this may take a while)..." &&
TERM=dumb th waifu2x.lua -m noise_scale -noise_level 2 \
    -i "/tmp/waifu2x-$USER.$hash-in.$ext" \
    -o "/tmp/waifu2x-$USER.$hash-out.png"
EOF
rsync -bPv "$remote:/tmp/waifu2x-$USER.$hash-out.png" "$output"
printf "%s\n" "Output saved to: $output"
