#!/usr/bin/env python3
import argparse, asyncio, contextlib, os, signal, subprocess, sys

DESCRIPTION = """
Example usage:

    watch-run -- make

    watch-run foo.c bar.c -- ./run-tests.sh

"""

class UserError(Exception):
    pass

class AsyncChildProcess:
    def __init__(self, proc):
        self.proc = proc

    async def __aenter__(self):
        return self.proc

    async def __aexit__(self, exc_type, exc, tb):
        try:
            self.proc.terminate()
            await self.proc.wait()
        except Exception:
            pass

class Watcher:
    def __init__(self, paths, cmd):
        self.paths = paths
        self.cmd = cmd

    async def main(self):
        self.cond = asyncio.Condition()
        self.start = False
        monitor = asyncio.create_task(self.monitor())
        runner = asyncio.create_task(self.runner())
        done, pending = await asyncio.wait(
            [monitor, runner],
            return_when=asyncio.FIRST_EXCEPTION,
        )
        for task in pending:
            task.cancel()
        await asyncio.wait(pending)
        raise done.pop().exception()

    async def monitor(self):
        try:
            with open(os.devnull, "r") as fdevnull:
                try:
                    p = await asyncio.create_subprocess_exec(
                        "inotifywait", "-m", "-q", "-r",
                        "-e", "close_write", "--", *self.paths,
                        stdin=fdevnull,
                        stdout=subprocess.PIPE)
                except OSError as e:
                    raise UserError("Notifier failure: {}".format(e))
            async with AsyncChildProcess(p):
                async for line in p.stdout:
                    async with self.cond:
                        self.start = True
                        self.cond.notify()
                raise UserError("Notifier exited unexpectedly.")
        except UserError as e:
            sys.stderr.write("\x1b[31;1m[!] {}\x1b[0m\n".format(e))
            sys.stderr.flush()

    async def runner(self):
        while True:
            sys.stderr.write("\x1b[34;1m[~]\x1b[0;1m Building...\x1b[0m\n")
            sys.stderr.flush()
            try:
                try:
                    p = await asyncio.create_subprocess_exec(*self.cmd)
                except OSError as exc:
                    raise UserError("can't run command: {}".format(exc))
                async with AsyncChildProcess(p):
                    code = await p.wait()
                if code:
                    raise UserError("command exited with: {}".format(code))
            except UserError as e:
                sys.stderr.write("\x1b[31;1m[!] ERROR: {}\x1b[0m\n"
                                 .format(e))
                sys.stderr.flush()
            else:
                sys.stderr.write("\x1b[32;1m[o]\x1b[0;1m Watching...\x1b[0m\n")
                sys.stderr.flush()
            async with self.cond:
                await self.cond.wait_for(lambda: self.start)
                self.start = False

def parse_args():
    p = argparse.ArgumentParser(
        description=DESCRIPTION,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("paths", metavar="args", nargs="*", default=["."])
    args = sys.argv[1:]
    try:
        i = args.index("--")
    except ValueError:
        cmd = []
    else:
        cmd = args[(i + 1):]
        args = args[:i]
    args = p.parse_args(args)
    if not cmd:
        p.print_usage(sys.stderr)
        sys.stderr.write("{}: error: expected '--' followed by the command\n"
                         .format(p.prog))
        sys.stderr.flush()
        sys.exit(1)
    return args, cmd

args, cmd = parse_args()
try:
    asyncio.run(Watcher(paths=args.paths, cmd=cmd).main())
    sys.exit(1)
except KeyboardInterrupt:
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    os.kill(os.getpid(), signal.SIGINT)
