#!/usr/bin/env python
import argparse, json, sys
import yaml

p = argparse.ArgumentParser()
p.add_argument("file")
args = p.parse_args()
with open(args.file) as f:
    json.dump(yaml.safe_load(f), sys.stdout, indent=4)
sys.stdout.write("\n")
