#!/usr/bin/env python3
import argparse, datetime, json, sys
import yaml

def default(obj: object) -> str:
    if isinstance(obj, datetime.datetime):
        return str(obj)
    return obj

p = argparse.ArgumentParser()
p.add_argument("file")
args = p.parse_args()
with open(args.file) as f:
    json.dump(
        yaml.safe_load(f),
        sys.stdout,
        ensure_ascii=False,
        indent=4,
        default=default,
    )
sys.stdout.write("\n")
